version: "3.5"

networks:
  koomtact-network:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - WORKSPACE_USER=${DOCKER_WORKSPACE_USER}
        - WORKSPACE_INSTALL_COMPOSER=${DOCKER_WORKSPACE_INSTALL_COMPOSER}
        - WORKSPACE_COMPOSER_HASH=${DOCKER_WORKSPACE_COMPOSER_HASH}
        - WORKSPACE_INSTALL_ZSH=${DOCKER_WORKSPACE_INSTALL_ZSH}
        - WORKSPACE_GITHUB_SSH_KEY=${DOCKER_WORKSPACE_GITHUB_SSH_KEY}
        - HOST_GITCONFIG_PATH=${DOCKER_HOST_GITCONFIG_PATH}
        - HOST_SSH_PATH=${DOCKER_HOST_SSH_PATH}
        - PHP_VERSION=${DOCKER_PHP_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./:/workspace
      - ${DOCKER_HOST_GITCONFIG_PATH}:/home/${DOCKER_WORKSPACE_USER}/.gitconfig
      - ${DOCKER_HOST_SSH_PATH}:/home/${DOCKER_WORKSPACE_USER}/.ssh
    ports:
      - "9001:9001"
    expose:
      - "${DOCKER_PHP_FPM_PORT}"
    networks:
      - koomtact-network

  nginx:
    build: ./docker/nginx
    volumes:
      - ./:/workspace
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/nginx/sites:/etc/nginx/sites-available
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    networks:
      - koomtact-network

  mysql:
    image: mysql:${DOCKER_MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
      - MYSQL_USER=${DOCKER_MYSQL_USER}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    networks:
      - koomtact-network

  redis:
      build:
        context: ./docker/redis
        args:
          - REDIS_VERSION=${DOCKER_REDIS_VERSION}
      volumes:
        - ./docker/.data/redis:/data
      ports:
        - "${DOCKER_REDIS_PORT}:6379"
      networks:
        - koomtact-network
