<?php

namespace Tests\Feature;

use App\Handlers\CvsHandler;
use App\Models\Contact;
use App\Models\FileImport;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Tests\Traits\SampleFilesTrait;

class CvsHandlerTest extends TestCase
{
    use RefreshDatabase, SampleFilesTrait;

    protected CvsHandler $handler;

    public function test_get_form()
    {
        $this->assertIsArray($this->handler->getFrom());
        $this->assertEquals($this->handler->getFrom(), $this->getIncludeArray('sample_csv_header.php'));
    }

    public function test_get_to()
    {
        $contact = new Contact();
        $this->assertIsArray($this->handler->getTo($contact));
        $this->assertEquals(
            $this->handler->getTo($contact),
            $contact->getFillable()
        );
    }

    public function test_process()
    {
        $contact = new Contact();
        $this->assertEmpty($contact::all()->count());
        $this->handler->process(Contact::class);
        $this->assertTrue($contact::all()->count() > 0);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->handler = new CvsHandler(
            FileImport::factory()->create([
                'path' => $this->getPath('sample.csv'),
                'from_to' => $this->getIncludeArray('sample_from_to.php')
            ])
        );
    }
}
